name: aeolus_docs
channels:
- conda-forge
dependencies:
- python=3.7
# - cartopy
- iris=>2.2.1
- matplotlib<3,>=2
- metpy
- nbsphinx
- numpy
# - pytest
# - pyvista
- sphinx
- sphinx_rtd_theme
- tornado
- pip:
  - latlon23
